### ISSUE TITLE
Buffer do ADC não está sincronizado

### ISSUE THREAD

**Issue by renanmoreira17** [Tesla-UFMG/ECU#10]
https://github.com/Tesla-UFMG/ECU/blob/56b04e6ba24644ba9811f46fe627d8e35f889084/Core/Src/global_variables.c#L15

Essa variável é acessada em várias tarefas e, como é populada a partir do DMA, pode ser escrita a qualquer momento.
Como pode-se observar no exemplo abaixo:
https://github.com/Tesla-UFMG/ECU/blob/56b04e6ba24644ba9811f46fe627d8e35f889084/Core/Src/throttle.c#L20
O acesso aos elementos não é atômico, então é necessário que seja feita a sincronização desse acesso por meio de Locks e Semaphores.
A HAL fornece callbacks de ADC para DMA, como por exemplo `void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *)` e `void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *)` (stm32h7xx_hal_adc.h). Pode-se implementar um ou ambos desses callbacks para realizar a sincronização.

**Comment by renanmoreira17** [comment]
@Tesla-UFMG/controle

**Comment by FelTell** [comment]
Resolvido com #32
